### ISSUE TITLE
gradle bootJar报错了

### ISSUE THREAD

**Issue by liuxiaocong1212** [8enet/Charles-Crack#3]
报错信息如下：
`FAILURE: Build failed with an exception.

* Where:
Build file 'D:\A_work\Work\1-▒▒▒▒\Charles-Crack\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'Charles-Crack'.
> Failed to apply plugin [id 'org.springframework.boot']
   > Spring Boot plugin requires Gradle 4.0 or later. The current version is Gradle 2.10`
麻烦给看下啊

**Comment by ghost** [comment]
我擦，题主从来不看报错信息？该错误信息清楚地说明了 Spring Boot plugin 依赖 Gradle 4.0 或者之后的版本，而你的 Gradle 版本是 2.10，所以你需要做的事是升级 Gradle 版本

**Comment by 8enet** [comment]
升级gradle 版本到4.0+
