### ISSUE TITLE
用注册码吧，稳的一批。

### ISSUE THREAD

**Issue by pengzhile** [8enet/Charles-Crack#5]
Registered Name: https://zhile.io
License Key: 48891cf209c6d32bf4

通杀目前4.2.6及以下任何版本。

**Comment by 8enet** [comment]
感谢，本项目仅提供一种破解方法，主要特点可以自定义注册名称，不关心这些的话用直接用注册码确实是更好的选择。

**Comment by tututu-patch** [comment]
@pengzhile 你的博客开个rss吧。

**Comment by pengzhile** [comment]
> @pengzhile 你的博客开个rss吧。

开了。
